#include "map.hpp"

Map::Map(sf::Vector2<double> anchor, sf::Vector2<int> sze, int width) {
  anchorPoint = anchor;
  size = sze;
  tileWidth = width;
  
  mapBody = new PacTile* [size.x*size.y];
}

// Private
// Compute index from point (in pixels), anchorPoint, and tileWidth
int Map::getIndexFromPoint(sf::Vector2<double> point) {
  sf::Vector2<double> tempCoord = sf::Vector2<double>(point.x, point.y);
  
  // Normalize the coordinate to our map's origin
  tempCoord.x = point.x - anchorPoint.x;
  tempCoord.y = point.y - anchorPoint.y;
  
  // Normalize the coordinate to our map's tile width
  tempCoord.x = tempCoord.x/tileWidth;
  tempCoord.y = tempCoord.y/tileWidth;
  
  // Normalize the entire coordinate into a 1D index
  return tempCoord.y*size.x + tempCoord.x;
}

// Public
void Map::setTile(sf::Vector2<int> indexes, sf::Sprite spr, sf::String typeOfTile) {
  PacTile* tempTile = new PacTile(spr, typeOfTile);
  int realIndex = indexes.y*size.x + indexes.x;
  mapBody[realIndex] = tempTile;
}

void Map::setTile(sf::Vector2<int> indexes, PacTile* tile) {
  // Since we are smashing a 2D array into a 1D array, the real index is the number of rows down (The y pos * the row width) plus how many columns over (the x pos)
  int realIndex = indexes.y*size.x + indexes.x;
  mapBody[realIndex] = tile;
}

PacTile* Map::getTileAtIndex(sf::Vector2<int> pos) {
  int realIndex = pos.y*size.x + pos.x;
  return mapBody[realIndex];
}

PacTile* Map::getTileAtPoint(sf::Vector2<double> point) {
  int realIndex = getIndexFromPoint(point);
  return mapBody[realIndex];
}

sf::Vector2<int> Map::convertPositionToIndex(double x, double y) {
  int realIndex = getIndexFromPoint(sf::Vector2<double>(x, y));
  int xComponent = realIndex%size.x;
  int yComponent = realIndex/size.x;
  
  return sf::Vector2<int>(xComponent, yComponent);
}

sf::Vector2<int> Map::getSize() {
  return size;
}

sf::Vector2<double> Map::getAnchor() {
  return anchorPoint;
}

int Map::getTileWidth() {
  return tileWidth;
}

void Map::configureMap(std::map<sf::String, PacTile*> tileSet) {
  setTile(sf::Vector2<int>(0, 0), tileSet["outer_top_left_corner"]);
  setTile(sf::Vector2<int>(1, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(2, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(3, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(4, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(5, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(6, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(7, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(8, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(9, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(10, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(11, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(12, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(13, 0), tileSet["weird_north_left_corner"]);
  setTile(sf::Vector2<int>(14, 0), tileSet["weird_north_right_corner"]);
  setTile(sf::Vector2<int>(15, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(16, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(17, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(18, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(19, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(20, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(21, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(22, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(23, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(24, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(25, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(26, 0), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(27, 0), tileSet["top_right_corner"]);
  
  setTile(sf::Vector2<int>(0, 1), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(8, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 1), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 1), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(21, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 1), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 1), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 2), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 2), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 2), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(3, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(4, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(5, 2), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(6, 2), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 2), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(8, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(9, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(10, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(11, 2), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(12, 2), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 2), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 2), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 2), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 2), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(17, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(18, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(19, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(20, 2), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(21, 2), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 2), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(23, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(24, 2), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(25, 2), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(26, 2), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 2), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 3), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 3), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(3, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 3), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(6, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 3), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 3), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(12, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 3), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 3), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 3), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(17, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 3), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 3), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(23, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 3), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(26, 3), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 3), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 4), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 4), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 4), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(3, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(4, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(5, 4), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(6, 4), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 4), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(8, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(9, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(10, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(11, 4), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(12, 4), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 4), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(14, 4), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(15, 4), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 4), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(17, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(18, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(19, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(20, 4), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(21, 4), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 4), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(23, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(24, 4), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(25, 4), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(26, 4), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 4), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 5), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(8, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(21, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 5), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 5), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 6), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 6), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 6), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(3, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(4, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(5, 6), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(6, 6), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 6), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(8, 6), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(9, 6), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 6), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(11, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(12, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(13, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(14, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(15, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(16, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(17, 6), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(18, 6), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 6), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(20, 6), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(21, 6), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 6), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(23, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(24, 6), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(25, 6), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(26, 6), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 6), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 7), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 7), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 7), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(3, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(4, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(5, 7), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(6, 7), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 7), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 7), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 7), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 7), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(11, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(12, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(13, 7), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(14, 7), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(15, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(16, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(17, 7), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(18, 7), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 7), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 7), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 7), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 7), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(23, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(24, 7), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(25, 7), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(26, 7), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 7), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 8), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 8), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 8), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 8), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 8), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 8), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 8), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 8), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 8), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 9), tileSet["bottom_left_corner"]);
  setTile(sf::Vector2<int>(1, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(2, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(3, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(4, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(5, 9), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(6, 9), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 9), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 9), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(9, 9), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(10, 9), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(11, 9), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(12, 9), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 9), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 9), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 9), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 9), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(17, 9), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(18, 9), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(19, 9), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(20, 9), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 9), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 9), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(23, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(24, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(25, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(26, 9), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(27, 9), tileSet["bottom_right_corner"]);
  
  setTile(sf::Vector2<int>(0, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 10), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(6, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 10), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 10), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(9, 10), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(10, 10), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(11, 10), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(12, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 10), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(14, 10), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(15, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 10), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(17, 10), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(18, 10), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(19, 10), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(20, 10), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 10), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(23, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 10), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 10), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 11), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(6, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 11), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 11), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 11), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 11), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 11), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(23, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 11), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 11), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 12), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(6, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 12), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 12), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 12), tileSet["house_top_right_corner"]);
  setTile(sf::Vector2<int>(11, 12), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(12, 12), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(13, 12), tileSet["door"]);
  setTile(sf::Vector2<int>(14, 12), tileSet["door"]);
  setTile(sf::Vector2<int>(15, 12), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(16, 12), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(17, 12), tileSet["house_top_left_corner"]);
  setTile(sf::Vector2<int>(18, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 12), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 12), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 12), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(23, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 12), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 12), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(1, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(2, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(3, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(4, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(5, 13), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(6, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 13), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(8, 13), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(9, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 13), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(11, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 13), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(18, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 13), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(20, 13), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(21, 13), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 13), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(23, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(24, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(25, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(26, 13), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(27, 13), tileSet["top_edge"]);
  
  setTile(sf::Vector2<int>(0, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(8, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 14), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(11, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 14), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(18, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(21, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 14), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 14), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(1, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(2, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(3, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(4, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(5, 15), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(6, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 15), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(8, 15), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(9, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 15), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(11, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 15), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(18, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 15), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(20, 15), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(21, 15), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 15), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(23, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(24, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(25, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(26, 15), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(27, 15), tileSet["bottom_edge"]);
  
  setTile(sf::Vector2<int>(0, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 16), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(6, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 16), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 16), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 16), tileSet["house_bottom_left_corner"]);
  setTile(sf::Vector2<int>(11, 16), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(12, 16), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(13, 16), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(14, 16), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(15, 16), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(16, 16), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(17, 16), tileSet["house_bottom_right_corner"]);
  setTile(sf::Vector2<int>(18, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 16), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 16), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 16), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(23, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 16), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 16), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 17), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(6, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 17), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 17), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 17), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 17), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 17), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(23, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 17), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 17), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(1, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 18), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(6, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 18), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 18), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 18), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(11, 18), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(12, 18), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(13, 18), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(14, 18), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(15, 18), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(16, 18), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(17, 18), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(18, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 18), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 18), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 18), tileSet["right_edge"]);
  setTile(sf::Vector2<int>(23, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 18), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 18), tileSet["floor"]);
  
  setTile(sf::Vector2<int>(0, 19), tileSet["outer_top_left_corner"]);
  setTile(sf::Vector2<int>(1, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(2, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(3, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(4, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(5, 19), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(6, 19), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 19), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(8, 19), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(9, 19), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 19), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(11, 19), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(12, 19), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(13, 19), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(14, 19), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(15, 19), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(16, 19), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(17, 19), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(18, 19), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 19), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(20, 19), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(21, 19), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 19), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(23, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(24, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(25, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(26, 19), tileSet["top_edge"]);
  setTile(sf::Vector2<int>(27, 19), tileSet["top_right_corner"]);
  
  setTile(sf::Vector2<int>(0, 20), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(8, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 20), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 20), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(21, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 20), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 20), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 21), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 21), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 21), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(3, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(4, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(5, 21), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(6, 21), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 21), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(8, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(9, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(10, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(11, 21), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(12, 21), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 21), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 21), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 21), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 21), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(17, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(18, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(19, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(20, 21), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(21, 21), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 21), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(23, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(24, 21), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(25, 21), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(26, 21), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 21), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 22), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 22), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 22), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(3, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(4, 22), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(5, 22), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(6, 22), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 22), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(8, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(9, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(10, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(11, 22), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(12, 22), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 22), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(14, 22), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(15, 22), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 22), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(17, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(18, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(19, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(20, 22), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(21, 22), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 22), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(23, 22), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(24, 22), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(25, 22), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(26, 22), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 22), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 23), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 23), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(5, 23), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(6, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(8, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(21, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 23), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(23, 23), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(24, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 23), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 23), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 24), tileSet["weird_west_upper_corner"]);
  setTile(sf::Vector2<int>(1, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(2, 24), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(3, 24), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 24), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(5, 24), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(6, 24), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 24), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(8, 24), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(9, 24), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 24), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(11, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(12, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(13, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(14, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(15, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(16, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(17, 24), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(18, 24), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 24), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(20, 24), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(21, 24), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 24), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(23, 24), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(24, 24), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 24), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(26, 24), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(27, 24), tileSet["weird_east_upper_corner"]);
  
  setTile(sf::Vector2<int>(0, 25), tileSet["weird_west_lower_corner"]);
  setTile(sf::Vector2<int>(1, 25), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(2, 25), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(3, 25), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 25), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(5, 25), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(6, 25), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 25), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 25), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 25), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 25), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(11, 25), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(12, 25), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(13, 25), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(14, 25), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(15, 25), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(16, 25), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(17, 25), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(18, 25), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 25), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 25), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 25), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 25), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(23, 25), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(24, 25), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 25), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(26, 25), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(27, 25), tileSet["weird_east_lower_corner"]);
  
  setTile(sf::Vector2<int>(0, 26), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 26), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(8, 26), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(9, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 26), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 26), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 26), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(20, 26), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(21, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 26), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 26), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 27), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 27), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 27), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(3, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(4, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(5, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(6, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(7, 27), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(8, 27), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(9, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(10, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(11, 27), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(12, 27), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 27), tileSet["inner_right_edge"]);
  setTile(sf::Vector2<int>(14, 27), tileSet["inner_left_edge"]);
  setTile(sf::Vector2<int>(15, 27), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 27), tileSet["box_top_left_corner"]);
  setTile(sf::Vector2<int>(17, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(18, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(19, 27), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(20, 27), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(21, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(22, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(23, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(24, 27), tileSet["box_top_edge"]);
  setTile(sf::Vector2<int>(25, 27), tileSet["box_top_right_corner"]);
  setTile(sf::Vector2<int>(26, 27), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 27), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 28), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 28), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 28), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(3, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(4, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(5, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(6, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(7, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(8, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(9, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(10, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(11, 28), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(12, 28), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 28), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(14, 28), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(15, 28), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 28), tileSet["box_bottom_left_corner"]);
  setTile(sf::Vector2<int>(17, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(18, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(19, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(20, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(21, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(22, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(23, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(24, 28), tileSet["box_bottom_edge"]);
  setTile(sf::Vector2<int>(25, 28), tileSet["box_bottom_right_corner"]);
  setTile(sf::Vector2<int>(26, 28), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 28), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 29), tileSet["left_edge"]);
  setTile(sf::Vector2<int>(1, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(2, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(3, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(4, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(5, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(6, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(7, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(8, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(9, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(10, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(11, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(12, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(13, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(14, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(15, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(16, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(17, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(18, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(19, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(20, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(21, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(22, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(23, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(24, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(25, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(26, 29), tileSet["floor"]);
  setTile(sf::Vector2<int>(27, 29), tileSet["right_edge"]);
  
  setTile(sf::Vector2<int>(0, 30), tileSet["bottom_left_corner"]);
  setTile(sf::Vector2<int>(1, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(2, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(3, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(4, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(5, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(6, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(7, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(8, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(9, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(10, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(11, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(12, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(13, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(14, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(15, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(16, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(17, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(18, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(19, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(20, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(21, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(22, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(23, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(24, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(25, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(26, 30), tileSet["bottom_edge"]);
  setTile(sf::Vector2<int>(27, 30), tileSet["bottom_right_corner"]);
}

void Map::deleteTile(sf::Vector2<int> indexes) {
  int realIndex = indexes.y*size.x + indexes.x;
  delete mapBody[realIndex];
  mapBody[realIndex] = NULL;
}

void Map::deleteAllTiles() {
  for (int i = 0; i < size.x*size.y; i++) {
    if (mapBody[i] != NULL) {
      delete mapBody[i];
      mapBody[i] = NULL;
    }
  }
}